export const GET_ALL_CARDS_REQUEST = "GET_ALL_CARDS_REQUEST";
export const GET_ALL_CARDS_SUCCESS = "GET_ALL_CARDS_SUCCESS";
export const GET_ALL_CARDS_FAIL = "GET_ALL_CARDS_FAIL";

export const GET_CARD_REQUEST = "GET_CARD_REQUEST";
export const GET_CARD_SUCCESS = "GET_CARD_SUCCESS";
export const GET_CARD_FAIL = "GET_CARD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
